variable "name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "web_host_name" {}
variable "web_username" {}
variable "web_os_password" {}
variable "app_host_name" {}
variable "app_username" {}
variable "app_os_password" {}
variable "primary_database" {}
variable "primary_database_admin" {}
variable "primary_database_password" {}
variable "primary_database_version" {}
variable "gateway_configuration_prefix" {}
variable "sku_type" {}
variable "public_ip_version" {}
variable "ip_allocation_method" {}
